### PR TITLE
Bump package versions

### PR DESCRIPTION
**Pull request by flamingbear**
Bumps packages

~~Also deprecates python 3.7 (EOL: Ends in 2 months and 2 weeks (27 Jun 2023))~~

## Jira Issue ID

DAS-1764 (tangentally)

## Description

The main thing is to bump the package versions, but most importantly is the
python-dateutil. the existing `-python-dateutil ~= 2.7.5` causes a lot of
problems with other geo python libraries.  I have had a number of issues with
xarray and pandas that require a ~2.8 version.

## Local Test Steps

I'm not sure how you generally test these.  I created virtual environments for
python 3.8, 3.9, and 3.10 and and installed the dependecies with `make install`
and `make install-example`.  I ran the tests in each environment. Additionally
I ran the notebook under jupyter lab in my 3.10 environment.

Let me know if there are other tests I should do. The tests seem to run on 3.6 to 3.10 (counter to the README)

## PR Acceptance Checklist
~~* [ ] Acceptance criteria met~~
* [X] Tests added/updated (if needed) and passing
~~* [ ] Documentation updated (if needed)~~

### CODE REVIEW

**Comment by chris-durbin** [comment]
@ygliuvt - we should sanity check generate documentation using readthedocs still works on this branch.

Also side note to us, but our PRs run builds on 3.6, 3.7, and 3.8. Should we update our actions to different versions?

**Review by chris-durbin — APPROVED** [review]
I tested out the branch with read the docs and all the documentation still generates fine.

**Comment by flamingbear** [comment]
Is it mergable with the snyk error? Or should I ignore it?

**Review by ygliuvt — APPROVED** [review]

**Comment by ygliuvt** [comment]
Yes, you can ignore it.
> Is it mergable with the snyk error? Or should I ignore it?

**Pull request merged**
